updated README.md setup.py and zrp/about.py
zestai/zrp pull request #31
Opened 2022-09-18 23:23 UTC by PiotrekZak

2022-09-19 04:13 UTC, kasey-zest requested changes
need to update versions before moving ahead with the release

2022-09-19 04:13 UTC, kasey-zest commented on setup.py
> +    version="0.4.0",
version 0.3.2

2022-09-19 04:13 UTC, kasey-zest commented on zrp/about.py
> +__version__ = "0.4.0"
version 0.3.2

2022-09-21 13:53 UTC, PiotrekZak commented on setup.py
> +    version="0.4.0",
done

2022-09-21 13:53 UTC, PiotrekZak commented on zrp/about.py
> +__version__ = "0.4.0"
done

2022-09-21 14:18 UTC, kasey-zest approved these changes

2022-09-21 15:09 UTC, merged